name: "update-release-tags"
description: "Update Release version tag to alias"
branding:
  icon: check-circle
  color: green

inputs:
  token:
    description: Github Token
    required: true
    default: ${{ github.token }}

  version_tags:
    descrption: Link from version tag
    requied: true

runs:
  using: node20
  main: index.js