name: "Add PR comment"
description: "Add PR comment for bot"
branding:
  icon: git-pull-request
  color: blue
inputs:
  token: 
    description: Github Token
    required: false
    default: ${{ github.token }}

  pr_number:
    description: PR number
    required: false
    default: ${{ github.event.pull_request.number }}
  message:
    description: Add comment
    required: true
  bot-reviewer:
    description: Add bot reviewer
    required: false
    default: ${{ github.actor }}

runs:
  using: node20
  main: index.js
