name: "Add Issue comment"
description: "Add Issue comment for bot"
branding:
  icon: message-square
  color: blue
inputs:
  token: 
    description: Github Token
    required: false
    default: ${{ github.token }}

  message:
    description: Add comment
    required: true
runs:
  using: node20
  main: index.js
