name: Update Release Tags
run-name: Move ${{ github.event.inputs.major_version }} to ${{ github.event.inputs.target }}

on:
 workflow_dispatch:
    inputs:
      target:
        description: The tag or reference to use
        required: true
      major_version:
        type: choice
        description: The major version to update
        options:
            - v2
            - v1

jobs:
  tag:
      runs-on: ubuntu-latest
      steps:
        - name: Generating Instant Token
          uses: actions/create-github-app-token@v1
          id: genrate-token
          with:
            app-id: ${{ secrets.APP_ID }}
            private-key: ${{ secrets.APP_PEM }}

        - uses: actions/checkout@v3
          with:
            fetch-depth: 0
        - name: Git config
          run: |
            git config user.name "Ardentcats"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

        - name: Tag new Target (${{ github.event.inputs.target }} -> ${{ github.event.inputs.major_version }})
          run: |
            git tag -f ${{ github.event.inputs.major_version }} ${{ github.event.inputs.target }}

        - name: Push new Tag
          run: |
            git remote set-url origin "https://x-access-token:${{ steps.genrate-token.outputs.token }}@github.com/${GITHUB_REPOSITORY}"
            git push origin ${{ github.event.inputs.major_version }} --force
          