name: Update Release Tags
run-name: Move ${{ github.event.inputs.target }} to ${{ github.event.inputs.major_version }}

on:
 workflow_dispatch:
    inputs:
      target:
        description: The tag or reference to use
        required: true

      major_version:
        description: The tag major version
        required: true
jobs:
  tag:
      runs-on: ubuntu-latest
      steps:
        - name: Generating Instant Token
          uses: actions/create-github-app-token@v1
          id: generate-token
          with:
            app-id: ${{ secrets.APP_ID }}
            private-key: ${{ secrets.APP_PEM }}

        - uses: actions/checkout@v3
          with:
            token: ${{ steps.generate-token.outputs.token }}
            fetch-depth: 0

        - name: Tag new Target (${{ github.event.inputs.target }} -> ${{ github.event.inputs.major_version }})
          env:
            GH_TOKEN: ${{ steps.generate-token.outputs.token }}
          run: |
            git tag -fa ${{ github.event.inputs.major_version }} ${{ github.event.inputs.target }} \
              -m "${{ github.event.inputs.major_version }} Alias routeing ${{ github.event.inputs.target }} "

        - name: Push new Tag
          run: |
            git push origin --tags --force
          