name: Update Release Tags
run-name: Update Major version link to ${{ github.event.inputs.target }}
#run-name: Move ${{ github.event.inputs.target }} to ${{ github.event.inputs.major_version }}

on:
 workflow_dispatch:
    inputs:
      target:
        description: The tag or reference to use
        required: true
      # major_version:
      #   type: choice
      #   description: The major version to update
      #   options:
      #       - v2
      #       - v1

jobs:
  tag:
      runs-on: ubuntu-latest
      steps:
        - name: Generating Instant Token
          uses: actions/create-github-app-token@v1
          id: generate-token
          with:
            app-id: ${{ secrets.APP_ID }}
            private-key: ${{ secrets.APP_PEM }}

        - uses: actions/checkout@v3
          with:
            token: ${{ steps.generate-token.outputs.token }}
            fetch-depth: 0
            ref: res/tags/${{ github.event.inputs.target }}

        - name: Update Major Tags
          uses: ./update-release-tags/
          with:
            token: ${{ steps.generate-token.outputs.token }}
            version_tags: ${{ github.event.inputs.target }}

        # - name: Tag new Target (${{ github.event.inputs.target }} -> ${{ github.event.inputs.major_version }})
        #   run: |
        #     git tag -f ${{ github.event.inputs.major_version }} ${{ github.event.inputs.target }}

        # - name: Push new Tag
        #   run: |
        #     git push origin --tags --force
          